"""Añade campo created a Post

Revision ID: 626ecb9772a2
Revises: e70f3fcfda77
Create Date: 2020-03-30 23:58:58.832559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '626ecb9772a2'
down_revision = 'e70f3fcfda77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'created')
    # ### end Alembic commands ###
